let resumeData = {
    "imagebaseurl":"images/portfolio/coffee.jpg",
    "name": "Neel Narvankar",
    "role": "Software and Full Stack Engineer",
    "linkedinId":"https://www.linkedin.com/in/neelnarvankar30/",
    "skypeid": "Your skypeid",
    "roleDescription": "",
        "socialLinks":[
        {
          "name":"linkedin",
          "url":"https://www.linkedin.com/in/neelnarvankar30/",
          "className":"fa fa-linkedin"
        },
        {
          "name":"github",
          "url":"https://github.com/neelnarvankar30",
          "className":"fa fa-github"
        },
        {
          "name":"skype",
          "url":"",
          "className":"fa fa-twitter"
        }
      ],
    "aboutme":"Graduate Computer Science student with a focus on Software Development and Full Stack Engineering. My professional goal is to apply my skills towards designing, developing, testing, and implementing high-quality Software. In addition to my technical interests, I have a love for helping others through mentoring.",
    "address":"9451 Lee Hwy, Fairfax VA",
    "contact":"703-341-9457",
    "email":"neelnarvankar30@gmail.com",
    "website":"",
    "education":[
      {
        "UniversityName":"George Mason University",
        "specialization":"Masters in Computer Science",
        "MonthOfPassing":"May",
        "YearOfPassing":"2021",
        "Achievements":""
      },
      {
        "UniversityName":"University of Mymbai",
        "specialization":"Bachelors in Information Iechnology",
        "MonthOfPassing":"May",
        "YearOfPassing":"2019",
        "Achievements":""
      }
    ],
    "work":[
      {
        "CompanyName":"Graduate Teaching Assistant",
        "specialization":"C#, ASP.NET, JavaScript, AWS",
        "MonthOfLeaving":"August",
        "YearOfLeaving":"2020 - Present",
        // "Achievements":" ● Responsible for instructing and helping students in development and programming applications using ASP.NET in Cloud, and for coaching undergraduate students to develop skills in JavaScript and C#."
          "Achievements": ["Graduate Teaching Assistant and Lab Instructor for Application Development in AWS Cloud, C# application development, and Advanced Web Development at George Mason University.", "Responsible for instructing and helping students in development and programming applications using ASP.NET in Cloud, and for coaching undergraduate students to develop skills in JavaScript and C#."]
      },
      {
        "CompanyName":"React JS Developer",
        "specialization":"ReactJS, Bootstrap, HTML, CSS",
        "MonthOfLeaving":"Nov",
        "YearOfLeaving":"2020 - Jan 2021",
        // "Achievements":"● ● "
        "Achievements": ["Developed chrome extension using React JS called as Hypothesizer, this chrome extension acts as a debugging for react applications, it helps the developer to generate the correct hypothesis for what might be the problem.", "Created test cases for end-to-end testing of the application using React JS, used Bootstrap, working with JSON files to store, and retrieve the hypothesis"]
        
      },
      {
        "CompanyName":"Research Assistant",
        "specialization":"C# and VR Software Development",
        "MonthOfLeaving":"Dec",
        "YearOfLeaving":"2020 - Aug 2021",
        // "Achievements":"● . ● ● "
        "Achievements": ["Implemented a fully controlled and laboratory-validated ecological system in Virtual Reality using C# and Unity3d to help research capturing boundaries of peripersonal space at the individual subject level.",
        "Led the development of C# scripts for the successful implementation of the project, also used the XR development Tool kit, Developed the Per-Personal Space virtual model on VIVE 3D",
         "Achieved results that were helpful in successfully completing the experiment.",
          "Developed environment for ROKOKO smart-suit development. Programmed a Full-immersive smart-suit experience using Unity3d and Rokoko software."
        ]
        
      }
      ,
      {
        "CompanyName":"Research Assistant",
        "specialization":"Python developer (Human-Machine Interaction and Artificial Intelligence)",
        "MonthOfLeaving":"Dec",
        "YearOfLeaving":"2020 - Aug 2021",
        // "Achievements":"● ● ."
        "Achievements": ["Worked on Sony’s Aibo AI robot-dog to research Human-Machine Interaction. Wrote Web API’s to train the robot using Python. ",
        "Programmed Aibo AI Robot using Python to interact with humans, Programmed/trained Aibo for Speech recognition using Cognitive Phrases, Aibo was able to perform actions by speech recognition. ", 
        "Developed and maintained a Database of memories generated by Aibo. Maintained data integrity for the data collected by Aibo. Performed SQL commands for retrieving and maintaining data."]
        
      }
    ],
    
    "portfolio":[
      {
        "name":"Wha2Do",
        "description":"Android application for creating To-do list and day scheduler/planner",
        "imgurl":"images/wha2do.jpg",
        "url":"https://github.com/neelnarvankar30/wha2do"
      },
      {
        "name":"Sports Match Predictor",
        "description":"mobileapp",
        "imgurl":"images/Data.jpg",
        "url":"https://github.com/neelnarvankar30/IPL-MatchPredictor"
      },
      {
        "name":"Destine",
        "description":"A Travel Website",
        "imgurl":"images/destine.jpg",
        "url":"https://github.com/neelnarvankar30/Destine-A-Travel-Site"
      }      
    ],
  
  }
  
  export default resumeData